class Obstakel{
    constructor(x,y,xgrootte,ygrootte,obstakelkleur,obstakelsnelheid){
      this.x=x;
      this.y=y;
      this.xgrootte=xgrootte;
      this.ygrootte=ygrootte;
      this.obstakelkleur=obstakelkleur;
      this.obstakelsnelheid=random(1,5);
      this.level=1;
      this.isStopped=false;
      this.i=0;
    }
    move(){
      this.x+=this.obstakelsnelheid;
      textSize(50);
      text("Level "+this.level,(windowWidth/2)-100,120)
      if(this.isStopped==false){
      if(this.x>width){
        if(this.ygrootte>120){
          this.ygrootte=20
          this.y=windowHeight-20;
        }
        this.obstakelsnelheid=random(3,7);
        this.x=0;
        this.ygrootte+=10;
        this.y-=10;
        this.xgrootte+=5;
        this.level+=1;
        if (this.level%5==0){
          this.i+=1;
        }
      }
      }
      else{
        this.obstakelsnelheid=0;
      }
    }
    show(){
      fill(this.obstakelkleur);
      rect(this.x,this.y,this.xgrootte,this.ygrootte);
    }
    stop(){
      start=2;
      this.color='grey'
    }
    reset(){
      start=1;
      this.level=1;
      obstakel1.show();
      obstakel1.move();
      this.ygrootte=20;
      this.xgrootte=20;
      this.x=0;
      this.y=windowHeight-20;
      this.i=0;
    }
  }